settings:
  title: 'Status Page'
  url: 'https://https://dash.cloudflare.com' # used for Slack messages
  logo: flower.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare # unique identifier
    name: workers.cloudflare.com
    description: 'Workers Cloudflare' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Cloudflare'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: hochiminh-lightnode
    name: LightNode Sài Gòn
    description: 'Lightnode Saigon'
    url: 'https://lightnode-sgn-1.edge.nextdns.io/resolve?name=google.com' # URL to fetch
    method: GET 
    expectStatus: 200 
    followRedirect: false 
    linkable: false 

  - id: hochiminh-greencloud
    name: GreenCloud Sài Gòn
    description: 'Greencloud Sài Gòn'
    url: 'https://greencloud-sgn-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: zepto-sin
    name: Singapore Zepto
    description: 'zepto-sin-1.edge.nextdns.io'
    url: 'https://zepto-sin-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: vultr-sin
    name: Singapore Vultr
    description: 'vultr-sin-1.edge.nextdns.io'
    url: 'https://vultr-sin-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: anexia-sin
    name: Singapore Anexia
    description: 'anexia-sin-1.edge.nextdns.io'
    url: 'https://anexia-sin-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: anexia-hkg
    name: HongKong Anexia
    description: 'anexia-hkg-1.edge.nextdns.io'
    url: 'https://anexia-hkg-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 

  - id: zepto-hkg
    name: HongKong Zepto
    description: 'zepto-hkg-1.edge.nextdns.io'
    url: 'https://zepto-hkg-1.edge.nextdns.io/resolve?name=google.com'
    method: GET
    expectStatus: 200
    followRedirect: false 
    linkable: false 
